project:
  type: website
  output-dir: docs

website:
  title: "GSWEP4R Workshop"
  description: "`openstatsware` Workshop: Good Software Engineering Practice with R"
  site-url: https://openstatsware.github.io/shortcourse-seoul2026/
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: "house-fill"
      - href: listing.qmd
        text: Slides
        icon: "file-earmark-slides"
  page-footer:
    center:
      - text: "About `openstatsware`"
        href: https://openstatsware.org/
      - text: "Source Code on GitHub"
        href: https://github.com/openstatsware/shortcourse-seoul2026

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true

editor: source
