---
title: "Good Software Engineering Practice for R Packages"
---

<!--
Creators (initial authors):
- Daniel Sabanés Bové, https://github.com/danielinteractive/ and www.linkedin.com/in/danielsabanesbove/
- Friedrich Pahlke, https://github.com/fpahlke/ and www.linkedin.com/in/pahlke/
- Kevin Kunzmann, https://github.com/kkmann/ and https://www.linkedin.com/in/kevin-kunzmann-6486a11bb/
- Liming Li, https://github.com/clarkliming
- Joe Zhu, https://github.com/shajoezhu and http://www.linkedin.com/in/joe-zhu-464b5818
- Shuang Li, https://github.com/shuangli22
- Doug Kelkhoff, https://github.com/dgkf and https://www.linkedin.com/in/doug-kelkhoff/
- Philippe Boileau, https://github.com/philboileau and https://www.linkedin.com/in/philippe-boileau-773270205/
- Lukas A. Widmer, https://github.com/luwidmer and https://www.linkedin.com/in/lukas-widmer-37800b9b/
- Michael Mayer, https://www.linkedin.com/in/drmichaelmayer/
- Louisa H. Smith, https://www.linkedin.com/in/louisahsmith/
- Audrey T. Yeo, https://github.com/audreyyeoCH and https://www.linkedin.com/in/audrey-yeo-8000/
- Alessandro Gasparini, https://github.com/ellessenne and https://www.linkedin.com/in/ellessenne/

The Seoul 2026 version was edited by
- Daniel Sabanés Bové, https://github.com/danielinteractive/ and https://www.linkedin.com/in/danielsabanesbove/

License: In general unless otherwise stated, his work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.
To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.
The source files are hosted at https://github.com/openstatsware/shortcourse-seoul2026, which is forked from
https://github.com/openstatsware/shortcourse-iscb2025

Important: To use this work you must provide the name of the creators (initial authors), a link to the material, a link to the license, and indicate if changes were made.
-->

Welcome to the homepage of the short course *"Good Software Engineering Practice for R Packages"* at the Samsung Advanced Institute for Health Sciences & Technology (SAIHST), Sungkyunkwan University.
In this course you will learn hands-on skills and tools to engineer reliable R packages used in statistics.
The short course will be conducted in a full day and will be a mix of presentations and exercises.
Participants need to be comfortable with writing functions in R and use their own laptops as a prerequisite.

## Event Details

The event will be held on Friday, 17^th^ of July 2026, from 09:00 to 17:00 as an in-person workshop at the [Samsung Advanced Institute for Health Sciences & Technology (SAIHST), Sungkyunkwan University](https://saihst.skku.edu/).
The venue is _Hippocrates Hall_, 9^th^ floor, Building B, Samsung Life Insurance Ilwon Station Building.

The instructor for this workshop will be Daniel Sabanés Bové.
You can learn more about him in the [introduction section](slides/01_intro.qmd).

Please [register for the workshop](https://www.linkedin.com/safety/go/?url=https%3A%2F%2Flnkd.in%2FgJkx-jHy&urlhash=cE5D&mt=dtLTGjOro8tfUeghAMBspqQhl8E9Z7jmx_sit_XuyfkYoJMhFhHhHZKeEZiqaL23URYtOXeVo-KDS6_5DrkyCJdTVeGYTrtxJylR7qdXJ9WeEXdBFVv9an_6bg&isSdui=true&lipi=urn%3Ali%3Apage%3Ad_flagship3_detail_base%3BJomzNqmuRPWvTRjDRAAN%2FQ%3D%3D) in advance.

## Workshop Program

```{r}
#| echo: false

# TODO the times will need to be edited etc. in the csv file
readr::read_csv("slides/resources/program.csv", col_types = "cc") |>
  knitr::kable(col.names = c("", ""))
```

## Prerequisites & Technical Setup

Prior to the short course, participants should

-   Set up a (free) [GitHub.com account](https://github.com/join).
    - Note: There are other git platforms like [Gitlab](https://about.gitlab.com/) or [Bitbucket](https://bitbucket.org/), but we made the choice to go with GitHub.com for the course, since it is by far the most relevant git platform in the R community.
-   Install the latest [R](https://www.r-project.org/) and [RStudio](https://posit.co/download/rstudio-desktop/) software.
-   Install [Rtools](https://cran.r-project.org/bin/windows/Rtools/rtools44/rtools.html) (on Windows) or the [required tools](https://mac.r-project.org/tools/) (on macOS) to compile/build packages from source code.
-   Install additional R packages using the [installation script](slides/download/install.R).

For the course, participants are required to use their own laptop to be able to participate in the exercises.

### Optional Reading List

-   Excellent and very comprehensive [R Packages (2e)](https://r-pkgs.org/)
-   (Hardcore) description of how [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html) works
-   [GitHub 'Hello World'](https://docs.github.com/en/get-started/quickstart/hello-world) tutorial on how to use GitHub.com (does not require git command line knowledge)
-   Tutorial on [version control with git and SVN](https://docs.posit.co/ide/user/ide/guide/tools/version-control.html) (we will be using git)
-   Command line git mini intro [trygit](https://trygit.js.org/)
-   [First steps with git & github by RStudio](https://www.youtube.com/watch?v=jN6tvgt3GK8)
-   [RStudio cheatsheets/ Git & GitHub](https://github.com/rstudio/cheatsheets/blob/main/git-github.pdf)
-   [Excuse Me, Do You Have a Moment to Talk About Version Control?](https://doi.org/10.1080/00031305.2017.1399928) by Jennifer Bryan
-   [Version Control with Git](https://swcarpentry.github.io/git-novice/) course material by The Carpentries

## Material from Past Events

- [10th October 2025, Paris, FR](https://rconis.github.io/SnB2025-shortcourse/)
- [24th August 2025, Basel, CH](https://openstatsware.github.io/shortcourse-iscb2025/)
- [8th April 2025, Tokyo, JP](https://www.linkedin.com/posts/yuichi-nakajima-8984759a_r-package-development-workshop-by-daniel-activity-7305102975851511810-QPl_?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAeLiYUB2lCTxf2k2-ROB6XktxT7lyQYIaQ)
- [8th July 2024, Salzburg, AT](https://rconis.github.io/user2024-tutorial-gswep/)
- [18th and 19th April 2024, Zurich, CH](https://rconis.github.io/workshop-r-swe-zrh/)
- [16th and 17th October 2023, Montreal, QC, CA](https://openpharma.github.io/workshop-r-swe-mtl/)
- [26th September 2023, Rockville, MD, US](https://openpharma.github.io/workshop-r-swe-md/)
- [20th July 2023, San José, CA, US](https://openpharma.github.io/workshop-r-swe-sf/)
- [24th March 2023, Shanghai, CN](https://openpharma.github.io/workshop-r-swe/)
- [10th February 2023, Basel, CH](https://kkmann.github.io/workshop-r-swe/)
